#!/bin/bash
set -e

# Build script for Menace Modkit redistributables
# This creates component archives for GitHub releases and slim app builds

# Use system .NET SDK
DOTNET="dotnet"

echo "Building Menace Modkit redistributables..."
echo "Using: $($DOTNET --version)"
echo ""

# =============================================================================
# Extract version for release naming (ModkitVersion.cs is generated by MSBuild)
# =============================================================================

# Extract version from versions.json
if command -v jq &> /dev/null; then
  LOADER_VERSION=$(jq -r '.components.ModpackLoader.version' third_party/versions.json)
else
  LOADER_VERSION=$(grep -A1 '"ModpackLoader"' third_party/versions.json | grep '"version"' | sed 's/.*"version": *"\([^"]*\)".*/\1/')
fi
RELEASE_VERSION="$LOADER_VERSION"
BUILD_NUMBER=$(echo "$LOADER_VERSION" | cut -d. -f1)

echo "📦 Building v$BUILD_NUMBER ($LOADER_VERSION)..."
echo "   ModkitVersion.cs will be generated by MSBuild from versions.json"
echo ""

# Clean previous builds
rm -rf dist/
mkdir -p dist
mkdir -p dist/components

# =============================================================================
# Build DLLs
# =============================================================================

echo "📦 Building DataExtractor Mod..."
$DOTNET build src/Menace.DataExtractor -c Release -o dist/DataExtractor

# Update source tree bundled copy
cp dist/DataExtractor/Menace.DataExtractor.dll third_party/bundled/DataExtractor/

echo ""
echo "📦 Building ModpackLoader Mod..."
$DOTNET build src/Menace.ModpackLoader -c Release -o dist/ModpackLoader

# Framework assemblies: Roslyn 4.3.0 uses System.Collections.Immutable 6.0.0 which is
# DIFFERENT from MelonLoader 0.7.2's bundled 9.0.0. Different versions can coexist.
# See docs/DEPENDENCY-INVESTIGATION.md for the full investigation history.
#
# DO NOT upgrade Roslyn past 4.3.x - versions 4.4+ use S.C.I 8.0/9.0 which conflicts
# with MelonLoader's bundled 9.0.0 (same version from different paths = FileLoadException).
#
# .NET 6 considers these "inbox" assemblies and won't copy them automatically,
# so we copy from NuGet cache (netstandard2.0 builds work for MelonLoader).

echo "  → Copying framework dependencies from NuGet (version 6.0.0, different from MelonLoader's 9.0.0)..."
NUGET_CACHE="${HOME}/.nuget/packages"

# System.Collections.Immutable 6.0.0 - use netstandard2.0 build
if [ -f "${NUGET_CACHE}/system.collections.immutable/6.0.0/lib/netstandard2.0/System.Collections.Immutable.dll" ]; then
  cp "${NUGET_CACHE}/system.collections.immutable/6.0.0/lib/netstandard2.0/System.Collections.Immutable.dll" dist/ModpackLoader/
  echo "    ✓ System.Collections.Immutable.dll (6.0.0 from NuGet)"
fi

# System.Reflection.Metadata 6.0.0 - use netstandard2.0 build
if [ -f "${NUGET_CACHE}/system.reflection.metadata/6.0.0/lib/netstandard2.0/System.Reflection.Metadata.dll" ]; then
  cp "${NUGET_CACHE}/system.reflection.metadata/6.0.0/lib/netstandard2.0/System.Reflection.Metadata.dll" dist/ModpackLoader/
  echo "    ✓ System.Reflection.Metadata.dll (6.0.0 from NuGet)"
fi

# Keep bundled ModpackLoader payload in sync with build output to avoid dependency drift.
# We deploy all dependencies ourselves to avoid relying on MelonLoader's internal assemblies,
# which can vary between installations.
copy_modpackloader_payload() {
  local dest_dir="$1"
  mkdir -p "$dest_dir"
  rm -f "$dest_dir"/*.dll

  for dll in dist/ModpackLoader/*.dll; do
    [ -f "$dll" ] || continue
    cp "$dll" "$dest_dir/"
  done
}

# Update source tree bundled copy
copy_modpackloader_payload third_party/bundled/ModpackLoader

# =============================================================================
# Build GUI App
# =============================================================================

echo ""
echo "📦 Building GUI App..."

echo "  → Linux x64..."
# Roslyn DLLs excluded from bundle via csproj (ExcludeFromSingleFile) - they need to be on disk
$DOTNET publish src/Menace.Modkit.App -c Release -r linux-x64 --self-contained \
  -p:PublishSingleFile=true -p:DebugType=none -p:DebugSymbols=false \
  -o dist/gui-linux-x64

echo "  → Windows x64..."
# Roslyn DLLs excluded from bundle via csproj (ExcludeFromSingleFile) - they need to be on disk
$DOTNET publish src/Menace.Modkit.App -c Release -r win-x64 --self-contained \
  -p:PublishSingleFile=true -p:DebugType=none -p:DebugSymbols=false \
  -o dist/gui-win-x64

# =============================================================================
# Build MCP Server (must be before bundling step)
# =============================================================================

echo ""
echo "📦 Building MCP Server..."

echo "  → Linux x64..."
$DOTNET publish src/Menace.Modkit.Mcp -c Release -r linux-x64 --self-contained \
  -p:PublishSingleFile=true -p:DebugType=none -p:DebugSymbols=false \
  -o dist/mcp-linux-x64

echo "  → Windows x64..."
$DOTNET publish src/Menace.Modkit.Mcp -c Release -r win-x64 --self-contained \
  -p:PublishSingleFile=true -p:DebugType=none -p:DebugSymbols=false \
  -o dist/mcp-win-x64

# =============================================================================
# Bundle core files with GUI (versions.json for component downloads)
# =============================================================================

echo ""
echo "📦 Bundling core files with GUI..."

# Copy versions.json
mkdir -p dist/gui-linux-x64/third_party
mkdir -p dist/gui-win-x64/third_party
cp third_party/versions.json dist/gui-linux-x64/third_party/
cp third_party/versions.json dist/gui-win-x64/third_party/

# Copy bundled components as fallback (used when GitHub releases aren't available yet)
# Primary flow is download from GitHub; this enables pre-release testing
echo "  → Copying bundled components (fallback)..."
cp -r third_party/bundled dist/gui-linux-x64/third_party/
cp -r third_party/bundled dist/gui-win-x64/third_party/

# Copy MCP server binaries (optional component for AI assistant integration)
echo "  → Bundling MCP server..."
mkdir -p dist/gui-linux-x64/mcp
mkdir -p dist/gui-win-x64/mcp
cp dist/mcp-linux-x64/Menace.Modkit.Mcp dist/gui-linux-x64/mcp/
cp dist/mcp-win-x64/Menace.Modkit.Mcp.exe dist/gui-win-x64/mcp/
cp mcp/claude_config_example.json dist/gui-linux-x64/mcp/
cp mcp/claude_config_example.json dist/gui-win-x64/mcp/
cp mcp/README.md dist/gui-linux-x64/mcp/
cp mcp/README.md dist/gui-win-x64/mcp/

# =============================================================================
# Create Component Archives for GitHub Release
# =============================================================================

echo ""
echo "📦 Creating component archives..."

# DataExtractor (platform-independent)
echo "  → DataExtractor.zip..."
mkdir -p dist/component-DataExtractor
cp dist/DataExtractor/Menace.DataExtractor.dll dist/component-DataExtractor/
(cd dist/component-DataExtractor && zip -q -r ../components/DataExtractor.zip .)

# ModpackLoader + support dependencies (platform-independent)
echo "  → ModpackLoader.zip..."
mkdir -p dist/component-ModpackLoader
copy_modpackloader_payload dist/component-ModpackLoader
(cd dist/component-ModpackLoader && zip -q -r ../components/ModpackLoader.zip .)

# DotNetRefs (platform-independent)
if [ -d "third_party/bundled/dotnet-refs" ]; then
  echo "  → DotNetRefs.zip..."
  (cd third_party/bundled/dotnet-refs && zip -q -r ../../../dist/components/DotNetRefs.zip .)
fi

# MelonLoader (platform-specific)
if [ -d "third_party/bundled/MelonLoader" ]; then
  echo "  → MelonLoader-linux-x64.tar.gz..."
  tar -czf dist/components/MelonLoader-linux-x64.tar.gz \
    -C third_party/bundled/MelonLoader .

  echo "  → MelonLoader-win-x64.zip..."
  (cd third_party/bundled/MelonLoader && \
    zip -q -r ../../../dist/components/MelonLoader-win-x64.zip .)
fi

# AssetRipper (platform-specific)
if [ -d "third_party/bundled/AssetRipper/linux" ]; then
  echo "  → AssetRipper-linux-x64.tar.gz..."
  # Remove debug symbols first
  find third_party/bundled/AssetRipper -name "*.pdb" -delete 2>/dev/null || true
  find third_party/bundled/AssetRipper -name "*.dbg" -delete 2>/dev/null || true
  tar -czf dist/components/AssetRipper-linux-x64.tar.gz \
    -C third_party/bundled/AssetRipper/linux .
fi

if [ -d "third_party/bundled/AssetRipper/windows" ]; then
  echo "  → AssetRipper-win-x64.zip..."
  (cd third_party/bundled/AssetRipper/windows && \
    zip -q -r ../../../../dist/components/AssetRipper-win-x64.zip .)
fi

# DevMode modpack (source, platform-independent)
if [ -d "third_party/bundled/modpacks/DevMode-modpack" ]; then
  echo "  → DevMode.zip..."
  (cd third_party/bundled/modpacks/DevMode-modpack && \
    zip -q -r ../../../../dist/components/DevMode.zip . -x "*.obj" -x "bin/*" -x "obj/*")
fi

# TwitchSquaddies modpack (source, platform-independent)
if [ -d "third_party/bundled/modpacks/TwitchSquaddies-modpack" ]; then
  echo "  → TwitchSquaddies.zip..."
  (cd third_party/bundled/modpacks/TwitchSquaddies-modpack && \
    zip -q -r ../../../../dist/components/TwitchSquaddies.zip . -x "*.obj" -x "bin/*" -x "obj/*")
fi

# =============================================================================
# Generate Checksums and Manifest
# =============================================================================

echo ""
echo "📦 Generating checksums..."

cd dist/components

# Generate SHA256 for each archive
for file in *.zip *.tar.gz; do
  if [ -f "$file" ]; then
    sha256sum "$file" > "$file.sha256"
  fi
done

# Create manifest.json with all checksums
echo "  → manifest.json..."
echo "{" > manifest.json
echo '  "generatedAt": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'",' >> manifest.json
echo '  "components": {' >> manifest.json

first=true
for file in *.sha256; do
  if [ -f "$file" ]; then
    base="${file%.sha256}"
    hash=$(cat "$file" | cut -d' ' -f1)
    size=$(stat -c%s "$base" 2>/dev/null || stat -f%z "$base")
    if [ "$first" = true ]; then
      first=false
    else
      echo ',' >> manifest.json
    fi
    echo -n "    \"$base\": {\"sha256\": \"$hash\", \"size\": $size}" >> manifest.json
  fi
done
echo '' >> manifest.json
echo '  }' >> manifest.json
echo '}' >> manifest.json

cd ../..

# =============================================================================
# Build CLI Tool
# =============================================================================

echo ""
echo "📦 Building CLI Tool..."

echo "  → Linux x64..."
$DOTNET publish src/Menace.Modkit.Cli -c Release -r linux-x64 --self-contained \
  -p:PublishSingleFile=true -p:DebugType=none -p:DebugSymbols=false \
  -o dist/cli-linux-x64

echo "  → Windows x64..."
$DOTNET publish src/Menace.Modkit.Cli -c Release -r win-x64 --self-contained \
  -p:PublishSingleFile=true -p:DebugType=none -p:DebugSymbols=false \
  -o dist/cli-win-x64

# =============================================================================
# Create App Archives
# =============================================================================

echo ""
echo "📦 Creating app archives..."

cd dist
tar -czf menace-modkit-gui-linux-x64.tar.gz -C gui-linux-x64 .
zip -q -r menace-modkit-gui-win-x64.zip gui-win-x64/
tar -czf menace-modkit-cli-linux-x64.tar.gz -C cli-linux-x64 .
zip -q -r menace-modkit-cli-win-x64.zip cli-win-x64/
cd ..

# Note: docs are not bundled separately - accessible via the Docs section in the app UI

# =============================================================================
# Update tracked component archives
# =============================================================================

echo ""
echo "📦 Updating tracked component archives..."

mkdir -p third_party/components
cp dist/components/*.zip third_party/components/ 2>/dev/null || true
cp dist/components/*.tar.gz third_party/components/ 2>/dev/null || true

echo "  → Updated third_party/components/"

# =============================================================================
# Summary
# =============================================================================

echo ""
echo "✅ Build complete!"
echo ""
echo "App archives (dist/):"
ls -lh dist/*.tar.gz dist/*.zip 2>/dev/null | grep -v components || true

echo ""
echo "Component archives (third_party/components/):"
ls -lh third_party/components/*.zip third_party/components/*.tar.gz 2>/dev/null || true

echo ""
echo "📋 To release v$RELEASE_VERSION:"
echo ""
echo "   1. Review and commit the updated components:"
echo "      git add third_party/components/"
echo "      git commit -m \"Update components for v$RELEASE_VERSION\""
echo ""
echo "   2. Tag and push:"
echo "      git tag v$RELEASE_VERSION"
echo "      git push origin main v$RELEASE_VERSION"
echo ""
echo "   CI will create both releases automatically:"
echo "   - v$RELEASE_VERSION (app downloads for users)"
echo "   - components-v$RELEASE_VERSION (component archives for app)"
